default: &default
  # Tu correo de registro en flow.cl
  email_tienda : adel.cabrera.mesina@gmail.com

  # Ruta de la llave pública descargada desde flow.cl
  key_publica : 73BF325F-35E0-4435-8A01-330LDA6A1E1E

  # Modo de acceso a webpay, valores posibles:
  ### - Mostrar pasarela flow : f
  ### - Ingresar directamente a webpay : d
  tipo_pago : d

  # Medio de pago, valores posibles:
  ### - Solo Webpay : 1
  ### - Solo Servipag : 2
  ### - Todos los medios de pago : 9
  medio_pago : 1

  # Rutas por defecto
  ### Se pueden cambiar, pero deberás agregarlas manualmente a tu archivo config/routes.rb
  url_exito : /flow/exito
  url_fracaso : /flow/fracaso
  url_confirmacion : /flow/confirma

development:
  <<: *default
  # La URL de tu sitio en modo desarrollo, por default localhost
  url : http://localhost:3000

  # Ruta de tu llave privada de comercio en desarrollo
  key_privada : d419506456e8453b05c4a3ebdfdb48ae6c963104

  # Formulario de desarrollo de Flow
  url_form : https://sandbox.flow.cl/api/

production:
  <<: *default
  # La URL de tu sitio en modo producción
  url : http://misitio.cl

  # Ruta de tu llave privada de comercio en producción
  key_privada : d419506456e8453b05c4a3ebdfdb48ae6c963104

  # Formulario de desarrollo de Flow
  url_form : https://www.flow.cl/app/web/misDatos.php
